--------------------------------------------------------
--  DDL for Table AUDIT_ASPECT_LOG
--------------------------------------------------------

CREATE TABLE AUDIT_ASPECT_LOG
   ("ID" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"ERROR_DESC" VARCHAR2(3000 CHAR), 
	"REQUEST_TIME" VARCHAR2(255 CHAR), 
	"RESPONSE_TIME" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"UUID" VARCHAR2(255 CHAR), 
	"REQUEST_DATA" CLOB, 
	"RESPONSE_DATA" CLOB, 
	"REQ_TYPE" VARCHAR2(200 BYTE), 
	"EXT_SYS" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(2000 BYTE), 
	 CONSTRAINT "PK_AUDIT_ASPECT_LOG" PRIMARY KEY ("ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_EISE_DEV" 
 LOB ("REQUEST_DATA") STORE AS SECUREFILE (
  TABLESPACE "TBS_EISE_DEV" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("RESPONSE_DATA") STORE AS SECUREFILE (
  TABLESPACE "TBS_EISE_DEV" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

--------------------------------------------------------
--  DDL for Table ORDER_INVOICE_DETAILS
--------------------------------------------------------

CREATE TABLE ORDER_INVOICE_DETAILS
   ("ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"INVOICE_ID" VARCHAR2(200 BYTE), 
	"ORDER_ID" VARCHAR2(200 BYTE) , 
	"ORDER_DATE" TIMESTAMP (6), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(100 BYTE) , 
	"AMOUNT" NUMBER, 
	"AUDIT_UUID" VARCHAR2(100 BYTE), 
	CONSTRAINT "ORDER_INVOICE_DETAILS_PK" PRIMARY KEY ("ID")
	ENABLE 
	);
	 
--------------------------------------------------------
--  DDL for Table INVOICE_PAYMENT_METHODS
--------------------------------------------------------

CREATE TABLE INVOICE_PAYMENT_METHODS
   ("ID" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PAYMENT_METHOD_ID" VARCHAR2(200 BYTE), 
	"PAYMENT_METHOD_TYPE" VARCHAR2(50 BYTE), 
	"CARD_TYPE" VARCHAR2(20 BYTE), 
	"RESPONSE_PLAN" VARCHAR2(20 BYTE), 
	"ORDER_ID" VARCHAR2(40 BYTE), 
	"INVOICE_ID" VARCHAR2(100 BYTE), 
	"CURRENT_SETTLED" NUMBER, 
	"CURRENT_AUTH" NUMBER, 
	"ORDER_INVOICE_DETAILS_ID" VARCHAR2(200 BYTE), 
	CONSTRAINT "INVOICE_PAYMENT_METHODS_PK" PRIMARY KEY ("ID")
	ENABLE ,
	CONSTRAINT "INVOICE_PAYMENT_METHODS_FK1" FOREIGN KEY ("ORDER_INVOICE_DETAILS_ID")
	REFERENCES "ORDER_INVOICE_DETAILS" ("ID") ENABLE
	);
	  
--------------------------------------------------------
--  DDL for Table INVOICE_ITEM_DETAILS
--------------------------------------------------------
	  
CREATE TABLE INVOICE_ITEM_DETAILS
   (
	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TRANSACTION_TYPE" VARCHAR2(100 BYTE), 
	"INVOICE_ID" VARCHAR2(100 BYTE), 
	"INVOICE_LINE_ID" VARCHAR2(100 BYTE), 
	"INVOICE_ITEM_ID" VARCHAR2(100 BYTE), 
	"RESPONSE_PLAN" VARCHAR2(20 BYTE), 
	"PROMO_PLAN" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER, 
	"PAYMENT_AMOUNT" NUMBER,
	"INVOICE_PAYMENT_METHODS_ID" VARCHAR2(100 BYTE), 
	"PAYMENT_METHOD_ID" VARCHAR2(100 BYTE),
	CONSTRAINT "INVOICE_ITEM_DETAILS_PK" PRIMARY KEY ("ID")ENABLE, 
	CONSTRAINT "INVOICE_ITEM_DETAILS_FK1" FOREIGN KEY ("INVOICE_PAYMENT_METHODS_ID")
	REFERENCES "INVOICE_PAYMENT_METHODS" ("ID") ENABLE
   );
   
--------------------------------------------------------
--  DDL for Table INVOICE_CHARGE_DETAILS
--------------------------------------------------------
   
   CREATE TABLE INVOICE_CHARGE_DETAILS
   ("ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"INVOICE_PAYMENT_METHODS_ID" VARCHAR2(100 BYTE), 
	"CHARGE_TYPE" VARCHAR2(100 BYTE), 
	"CHARGE_DETAIL_ID" VARCHAR2(100 BYTE), 
	"PAYMENT_AMOUNT" NUMBER,
	"PAYMENT_METHOD_ID" VARCHAR2(100 BYTE),
	CONSTRAINT "INVOICE_CHARGE_DETAILS_PK" PRIMARY KEY ("ID") ENABLE, 
	CONSTRAINT "INVOICE_CHARGE_DETAILS_FK1" FOREIGN KEY ("INVOICE_PAYMENT_METHODS_ID")
	REFERENCES "INVOICE_PAYMENT_METHODS" ("ID") ENABLE
   ); 