--------------------------------------------------------
--  DDL for Table SAML_USER_INFO
--------------------------------------------------------

  CREATE TABLE SAML_USER_INFO
   (	"ID" VARCHAR2(100 BYTE), 
	"SESSION_ID" VARCHAR2(200 BYTE), 
	"USER_INFO" CLOB, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT SAML_USER_INFO_UK1 UNIQUE ("SESSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT),
  	 CONSTRAINT SAML_USER_INFO_PK PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_EISE_DEV" 
 LOB ("USER_INFO") STORE AS SECUREFILE (
  TABLESPACE "TBS_EISE_DEV" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;