--------------------------------------------------------
--  File created - Thursday-April-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIT_ASPECT_LOG
--------------------------------------------------------

  CREATE TABLE EISE_DEV.AUDIT_ASPECT_LOG
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"REQUEST_TIME" VARCHAR2(200), 
	"RESPONSE_TIME" VARCHAR2(200), 
	"STATUS" VARCHAR2(20), 
	"UUID" VARCHAR2(200), 
	"REQUEST_DATA" CLOB, 
	"RESPONSE_DATA" CLOB, 
	"URL" VARCHAR2(2000), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_DATE" TIMESTAMP (6)
   );

--------------------------------------------------------
--  Constraints for Table AUDIT_ASPECT_LOG
--------------------------------------------------------
  ALTER TABLE EISE_DEV.AUDIT_ASPECT_LOG ADD CONSTRAINT "AUDIT_ASPECT_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
