--------------------------------------------------------
--  File created - Thursday-May 07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INVOICE_ITEM_SETTLEMENT
--------------------------------------------------------
  CREATE TABLE EISE_DEV.INVOICE_ITEM_SETTLEMENT 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IIS_ID" NUMBER, 
	"PAYMENT_METHOD_TYPE" VARCHAR2(20), 
	"PAYMENT_METHOD_ID" VARCHAR2(20), 
	"CARDTYPE" VARCHAR2(20), 
	"AMOUNT" FLOAT(126)
   );
--------------------------------------------------------
--  DDL for Index INVOICE_ITEM_SETTLEMENT_PK
--------------------------------------------------------

  ALTER TABLE EISE_DEV.INVOICE_ITEM_SETTLEMENT ADD CONSTRAINT "INVOICE_ITEM_SETTLEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_ITEM_SETTLEMENT
--------------------------------------------------------

  ALTER TABLE EISE_DEV.INVOICE_ITEM_SETTLEMENT ADD CONSTRAINT "INVOICE_ITEM_SETTLEMENT_FK1" FOREIGN KEY ("IIS_ID")
	  REFERENCES "INVOICE_ITEM_DETAILS" ("ID") ENABLE;
