
spring:
  application:
    name: eise
  datasource: 
       url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
       username: 'eise'
       password: 'eise_dev' 
       driverClassName: oracle.jdbc.OracleDriver
    
server:
  port: 3003
  servlet:
    contextPath: /eise
  ssl:
    key-store: classpath:StoreTrust.jks
    key-store-password: uatstore
    key-alias: server_cert 


#JWT Config
jwt: 
  secret: e287cd9e2f114bc1b4687d5c32d25c95
  get: 
    token: 
      uri: /api/authenticate
  expiry: 28800
      
external:
   sys: mao
   
mao:
  username: eise
  password: ZWFnbGU=
  
aesToken:
  key: 7Npc3RLrpd76  

#key : xGAYCba+oUipNFylYgGnAA==  
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled:  false
      
logging:
  level:
    org.springframework: ERROR
    com.aafes.returns: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: logs/file.log      


eisesso:
  redirecturl: redirect test
  
pagination:
  reportlist: 10
     
#SAML properties

saml:
    sso:
        idp:
            metadata-location: classpath:/saml/FederationMetadata-azure.xml
        metadata-generator:
            entity-id: eagle-ecsettle-app.ecomint.aafes.com
        key-manager:
            private-key-der-location: classpath:/saml/adfs-logixal-sample.der
            public-key-pem-location: classpath:/saml/adfs-logixal-sample.cer
        default-success-url: /landing